define(["underscore"], 
function(_){
	function serverResponse() {
		return [
			{name: "Computer Science"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},			
			{name: "Computer Science"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},
			{name: "Computer Science"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},			
			{name: "Computer Science"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},			
			{name: "Computer Science"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},
			{name: "Computer Science"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},			
			{name: "Computer Science"},
			{name: "English"},
			{name: "History"},
			{name: "Electrical Engineering"},
			{name: "Psychology"},
			{name: "Nutrition"},
			{name: "Quad Copter"},
			{name: "Video Game Design"},
			{name: "Web Development"},
			{name: "Physical Education"},
			{name: "Business"},
		];
	}

	return serverResponse;
});
